### ISSUE TITLE
can not load the module on ubuntu 22.04 with lua5.2

### ISSUE THREAD

**Issue by laoshaw** [keplerproject/cgilua#19]
it always tried to find cgilua.lua or cgilua/init.lua but there are no such files in 6.x release

on a old cgilua release with lua-5.1, I saw cgilua.lua installed via luarocks, that worked fine.

am I missing something to use cgilua 6.x?

```lua
local cgilua = require "cgilua"
print("CGILua loaded successfully.")
```

**Comment by tomasguisasola** [comment]
This error is intentional.  It reveals that your script was launched incorrectly.

CGILua architecture works as a kind of replecement of Lua interpreter, thus you have to run `cgilua` and provide your script as a parameter.  CGILua is usually called by the Web Server to interpret the script file indicated in the URL requested.  Depending on the server there could be many possibilities to configure the **launching** of CGILua scripts.

I recommend you read the documentation, in particular:

https://lunarmodules.github.io/cgilua/manual.html

As an example, to launch a CGILua script as a cgi script with Apache, you have to:
- load mod_cgid.so;
- add `Options ExecCGI` to the directory where your CGILua scripts are stored;
- add `AddHandler cgi-script .lua .lp` to this same directory, indicating which extensions could be executed;
- add `#!/usr/bin/env cgilua.cgi` as the first line of each script (including `.lp`that must be called directly);
- make sure `cgilua.cgi` is accessible and executable (check the installation instructions);
- add execution attribute to each script (such as `chmod a+x *.lua`) to let them be executed by the server.

This is a raw installation.  There are many other possibilities...

Hope this helps!
